#!/bin/bash
##ENVIRONMENT SETTINGS; CHANGE WITH CAUTION
#SBATCH --export=NONE                #Do not propagate environment
#SBATCH --get-user-env=L             #Replicate login environment

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=tflearn 
#SBATCH --time=4:00:00              
#SBATCH --ntasks=28                  
#SBATCH --mem=20G                  
#SBATCH --output=output     
#SBATCH --gres=gpu:1                #Request 1 GPU per node can be 1 or 2
#SBATCH --partition=gpu              #Request the GPU partition/queue

##OPTIONAL JOB SPECIFICATIONS
#SBATCH --mail-type=ALL              #Send email on all job events
#SBATCH --mail-user=mostafa_karimi@tamu.edu    #Send all emails to email_address 

#First Executable Line
module load Anaconda/3-5.0.0.1
source activate my-tflearn
module load cuDNN/5.1-CUDA-8.0.44
python baseline.py
source deactivate my-tflearn
